namespace XREngine.VRClient
{
    public enum GameAction
    {
        Interact,
        Jump,
        ToggleMute,
        Grab,
        PlayspaceDragLeft,
        PlayspaceDragRight,
        ToggleMenu,
        ToggleMiniMenu,
        LeftHandPose,
        RightHandPose,
        LeftHandGrip,
        RightHandGrip,
        LeftHandTrigger,
        RightHandTrigger,
        LeftHandTrackpad,
        RightHandTrackpad,
        LeftHandTrackpadTouch,
        RightHandTrackpadTouch,
        LeftHandThumbstick,
        RightHandThumbstick,
        LeftHandA,
        RightHandA,
        LeftHandB,
        RightHandB,
        LeftHandX,
        RightHandX,
        LeftHandY,
        RightHandY,
    }
}
