namespace XREngine.Data.Rendering
{
    public enum EPixelFormat
    {
        UnsignedShort,
        UnsignedInt,
        ColorIndex,
        StencilIndex,
        DepthComponent,
        Red,
        Green,
        Blue,
        Alpha,
        Rgb,
        Rgba,
        Luminance,
        LuminanceAlpha,
        Bgr,
        Bgra,
        Rg,
        RgInteger,
        DepthStencil,
        RedInteger,
        GreenInteger,
        BlueInteger,
        AlphaInteger,
        RgbInteger,
        RgbaInteger,
        BgrInteger,
        BgraInteger
    }
}
